# Generated by Django 5.1.4 on 2025-09-24 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Z_Tribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
